Repository DO-SOPT-33rd-CDS-1/LongBlack_iOS, pull requests merged in 2023-11, with the labels that each got.

#2 Setting [#1] project setting
  LongBlack-iOS/LongBlack-iOS.xcodeproj/project.pbxproj
  LongBlack-iOS/LongBlack-iOS.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  LongBlack-iOS/LongBlack-iOS.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  LongBlack-iOS/LongBlack-iOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  LongBlack-iOS/LongBlack-iOS/Application/AppDelegate.swift
  LongBlack-iOS/LongBlack-iOS/Application/SceneDelegate.swift
  LongBlack-iOS/LongBlack-iOS/Base.lproj/LaunchScreen.storyboard
  LongBlack-iOS/LongBlack-iOS/Global/Extensions/UIColor+.swift
  LongBlack-iOS/LongBlack-iOS/Global/Extensions/UIStackView+.swift
  LongBlack-iOS/LongBlack-iOS/Global/Extensions/UIView+.swift
  LongBlack-iOS/LongBlack-iOS/Global/Literals/Image.swift
  LongBlack-iOS/LongBlack-iOS/Global/Literals/String.swift
  LongBlack-iOS/LongBlack-iOS/Global/Resources/Assets.xcassets/AccentColor.colorset/Contents.json
  LongBlack-iOS/LongBlack-iOS/Global/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  LongBlack-iOS/LongBlack-iOS/Global/Resources/Assets.xcassets/Contents.json
  LongBlack-iOS/LongBlack-iOS/Global/Resources/Color.swift
  LongBlack-iOS/LongBlack-iOS/Global/Resources/Font.swift
  LongBlack-iOS/LongBlack-iOS/Global/Resources/Font/Pretendard-Bold.otf
  LongBlack-iOS/LongBlack-iOS/Global/Resources/Font/Pretendard-Light.otf
  LongBlack-iOS/LongBlack-iOS/Global/Resources/Font/Pretendard-Medium.otf
  LongBlack-iOS/LongBlack-iOS/Global/Resources/Font/Pretendard-Regular.otf
  LongBlack-iOS/LongBlack-iOS/Global/Resources/Font/Pretendard-SemiBold.otf
  LongBlack-iOS/LongBlack-iOS/Global/Resources/Info.plist
  LongBlack-iOS/LongBlack-iOS/Presentation/BaseView.swift
  LongBlack-iOS/LongBlack-iOS/Presentation/BaseViewController.swift
  LongBlack-iOS/LongBlack-iOS/Presentation/ViewController.swift
Labels: setting, 채은

#7 [#3] TabBar 구현
  LongBlack-iOS/LongBlack-iOS.xcodeproj/project.pbxproj
  LongBlack-iOS/LongBlack-iOS/Application/SceneDelegate.swift
  LongBlack-iOS/LongBlack-iOS/Global/Extensions/CALayer+.swift
  LongBlack-iOS/LongBlack-iOS/Global/Extensions/UITabBar+.swift
  LongBlack-iOS/LongBlack-iOS/Global/Literals/Image.swift
  LongBlack-iOS/LongBlack-iOS/Global/Literals/String.swift
  LongBlack-iOS/LongBlack-iOS/Global/Resources/Assets.xcassets/ic_alarm_active.imageset/Contents.json
  LongBlack-iOS/LongBlack-iOS/Global/Resources/Assets.xcassets/ic_alarm_active.imageset/ic_alarm_active.png
  LongBlack-iOS/LongBlack-iOS/Global/Resources/Assets.xcassets/ic_alarm_active.imageset/ic_alarm_active@2x.png
  LongBlack-iOS/LongBlack-iOS/Global/Resources/Assets.xcassets/ic_alarm_active.imageset/ic_alarm_active@3x.png
  LongBlack-iOS/LongBlack-iOS/Global/Resources/Assets.xcassets/ic_alarm_default.imageset/Contents.json
  LongBlack-iOS/LongBlack-iOS/Global/Resources/Assets.xcassets/ic_alarm_default.imageset/ic_alarm_default.png
  LongBlack-iOS/LongBlack-iOS/Global/Resources/Assets.xcassets/ic_alarm_default.imageset/ic_alarm_default@2x.png
  LongBlack-iOS/LongBlack-iOS/Global/Resources/Assets.xcassets/ic_alarm_default.imageset/ic_alarm_default@3x.png
  LongBlack-iOS/LongBlack-iOS/Global/Resources/Assets.xcassets/ic_mypage_active.imageset/Contents.json
  LongBlack-iOS/LongBlack-iOS/Global/Resources/Assets.xcassets/ic_mypage_active.imageset/ic_mypage_active.png
  LongBlack-iOS/LongBlack-iOS/Global/Resources/Assets.xcassets/ic_mypage_active.imageset/ic_mypage_active@2x.png
  LongBlack-iOS/LongBlack-iOS/Global/Resources/Assets.xcassets/ic_mypage_active.imageset/ic_mypage_active@3x.png
  LongBlack-iOS/LongBlack-iOS/Global/Resources/Assets.xcassets/ic_mypage_default.imageset/Contents.json
  LongBlack-iOS/LongBlack-iOS/Global/Resources/Assets.xcassets/ic_mypage_default.imageset/ic_mypage_default.png
  LongBlack-iOS/LongBlack-iOS/Global/Resources/Assets.xcassets/ic_mypage_default.imageset/ic_mypage_default@2x.png
  LongBlack-iOS/LongBlack-iOS/Global/Resources/Assets.xcassets/ic_mypage_default.imageset/ic_mypage_default@3x.png
  LongBlack-iOS/LongBlack-iOS/Global/Resources/Assets.xcassets/ic_todaynote_active.imageset/Contents.json
  LongBlack-iOS/LongBlack-iOS/Global/Resources/Assets.xcassets/ic_todaynote_active.imageset/ic_todaynote_active.png
  LongBlack-iOS/LongBlack-iOS/Global/Resources/Assets.xcassets/ic_todaynote_active.imageset/ic_todaynote_active@2x.png
  LongBlack-iOS/LongBlack-iOS/Global/Resources/Assets.xcassets/ic_todaynote_active.imageset/ic_todaynote_active@3x.png
  LongBlack-iOS/LongBlack-iOS/Global/Resources/Assets.xcassets/ic_todaynote_default.imageset/Contents.json
  LongBlack-iOS/LongBlack-iOS/Global/Resources/Assets.xcassets/ic_todaynote_default.imageset/ic_todaynote_default.png
  LongBlack-iOS/LongBlack-iOS/Global/Resources/Assets.xcassets/ic_todaynote_default.imageset/ic_todaynote_default@2x.png
  LongBlack-iOS/LongBlack-iOS/Global/Resources/Assets.xcassets/ic_todaynote_default.imageset/ic_todaynote_default@3x.png
  LongBlack-iOS/LongBlack-iOS/Global/Resources/Color.swift
  LongBlack-iOS/LongBlack-iOS/Presentation/Home/HomeViewController.swift
  LongBlack-iOS/LongBlack-iOS/Presentation/Home/TabBar/HomeTabBar.swift
  LongBlack-iOS/LongBlack-iOS/Presentation/Home/TabBar/HomeTabBarItem.swift
  LongBlack-iOS/LongBlack-iOS/Presentation/Home/TabBar/HomeTabBarViewController.swift
  LongBlack-iOS/LongBlack-iOS/Presentation/Home/ViewController/AlarmViewController.swift
  LongBlack-iOS/LongBlack-iOS/Presentation/Home/ViewController/HomeViewController.swift
  LongBlack-iOS/LongBlack-iOS/Presentation/Home/ViewController/MyPageViewController.swift
Labels: feat, style, 채은

#14 [#9] home 화면 나머지 기능 추가 및 뷰 분리
  LongBlack-iOS/LongBlack-iOS.xcodeproj/project.pbxproj
  LongBlack-iOS/LongBlack-iOS/Global/Resources/Assets.xcassets/imgEventDummy1.imageset/Contents.json
  LongBlack-iOS/LongBlack-iOS/Global/Resources/Assets.xcassets/imgEventDummy1.imageset/Rectangle 28.png
  LongBlack-iOS/LongBlack-iOS/Global/Resources/Assets.xcassets/imgEventDummy1.imageset/Rectangle 28@2x.png
  LongBlack-iOS/LongBlack-iOS/Global/Resources/Assets.xcassets/imgEventDummy1.imageset/Rectangle 28@3x.png
  LongBlack-iOS/LongBlack-iOS/Global/Resources/Assets.xcassets/imgEventDummy1.imageset/Rectangle 45.png
  LongBlack-iOS/LongBlack-iOS/Global/Resources/Assets.xcassets/imgEventDummy1.imageset/Rectangle 45@2x.png
  LongBlack-iOS/LongBlack-iOS/Global/Resources/Assets.xcassets/imgEventDummy1.imageset/Rectangle 45@3x.png
  LongBlack-iOS/LongBlack-iOS/Global/Resources/Assets.xcassets/imgEventDummy2.imageset/Contents.json
  LongBlack-iOS/LongBlack-iOS/Global/Resources/Assets.xcassets/imgEventDummy2.imageset/Rectangle 28.png
  LongBlack-iOS/LongBlack-iOS/Global/Resources/Assets.xcassets/imgEventDummy2.imageset/Rectangle 28@2x.png
  LongBlack-iOS/LongBlack-iOS/Global/Resources/Assets.xcassets/imgEventDummy2.imageset/Rectangle 28@3x.png
  LongBlack-iOS/LongBlack-iOS/Global/Resources/Assets.xcassets/imgEventDummy2.imageset/Rectangle 46.png
  LongBlack-iOS/LongBlack-iOS/Global/Resources/Assets.xcassets/imgEventDummy2.imageset/Rectangle 46@2x.png
  LongBlack-iOS/LongBlack-iOS/Global/Resources/Assets.xcassets/imgEventDummy2.imageset/Rectangle 46@3x.png
  LongBlack-iOS/LongBlack-iOS/Global/Resources/Assets.xcassets/imgEventDummy3.imageset/Contents.json
  LongBlack-iOS/LongBlack-iOS/Global/Resources/Assets.xcassets/imgEventDummy3.imageset/Rectangle 44.png
  LongBlack-iOS/LongBlack-iOS/Global/Resources/Assets.xcassets/imgEventDummy3.imageset/Rectangle 44@2x.png
  LongBlack-iOS/LongBlack-iOS/Global/Resources/Assets.xcassets/imgEventDummy3.imageset/Rectangle 44@3x.png
  LongBlack-iOS/LongBlack-iOS/Global/Resources/Assets.xcassets/imgEventDummy3.imageset/Rectangle 47.png
  LongBlack-iOS/LongBlack-iOS/Global/Resources/Assets.xcassets/imgEventDummy3.imageset/Rectangle 47@2x.png
  LongBlack-iOS/LongBlack-iOS/Global/Resources/Assets.xcassets/imgEventDummy3.imageset/Rectangle 47@3x.png
  LongBlack-iOS/LongBlack-iOS/Presentation/Home/Button/HomeButton.swift
  LongBlack-iOS/LongBlack-iOS/Presentation/Home/Cell/EventImageCollectionViewCell.swift
  LongBlack-iOS/LongBlack-iOS/Presentation/Home/Cell/OpenNoteCollectionViewCell.swift
  LongBlack-iOS/LongBlack-iOS/Presentation/Home/Model/OpenNoteModel.swift
  LongBlack-iOS/LongBlack-iOS/Presentation/Home/View/HomeEventView.swift
  LongBlack-iOS/LongBlack-iOS/Presentation/Home/View/HomeMainView.swift
  LongBlack-iOS/LongBlack-iOS/Presentation/Home/View/HomeOpenNote.swift
  LongBlack-iOS/LongBlack-iOS/Presentation/Home/ViewController/AlarmViewController.swift
  LongBlack-iOS/LongBlack-iOS/Presentation/Home/ViewController/HomeViewController.swift
  LongBlack-iOS/LongBlack-iOS/Presentation/Home/ViewController/MyPageViewController.swift
Labels: feat, 채은

#16 [#15] network setting
  LongBlack-iOS/LongBlack-iOS.xcodeproj/project.pbxproj
  LongBlack-iOS/LongBlack-iOS/Global/Resources/Config.swift
  LongBlack-iOS/LongBlack-iOS/Global/Resources/Info.plist
Labels: setting, network, 채은

#20 [#12] LibraryView UI 구현
  LongBlack-iOS/LongBlack-iOS.xcodeproj/project.pbxproj
  LongBlack-iOS/LongBlack-iOS/Global/Literals/Image.swift
  LongBlack-iOS/LongBlack-iOS/Global/Literals/String.swift
  LongBlack-iOS/LongBlack-iOS/Global/Resources/Assets.xcassets/ic_arrow_left_small.imageset/Contents.json
  LongBlack-iOS/LongBlack-iOS/Global/Resources/Assets.xcassets/ic_arrow_left_small.imageset/ic_arrow_left.png
  LongBlack-iOS/LongBlack-iOS/Global/Resources/Assets.xcassets/ic_arrow_left_small.imageset/ic_arrow_left@2x.png
  LongBlack-iOS/LongBlack-iOS/Global/Resources/Assets.xcassets/ic_arrow_left_small.imageset/ic_arrow_left@3x.png
  LongBlack-iOS/LongBlack-iOS/Global/Resources/Assets.xcassets/ic_arrow_right_small.imageset/Contents.json
  LongBlack-iOS/LongBlack-iOS/Global/Resources/Assets.xcassets/ic_arrow_right_small.imageset/ic_arrow_right.png
  LongBlack-iOS/LongBlack-iOS/Global/Resources/Assets.xcassets/ic_arrow_right_small.imageset/ic_arrow_right@2x.png
  LongBlack-iOS/LongBlack-iOS/Global/Resources/Assets.xcassets/ic_arrow_right_small.imageset/ic_arrow_right@3x.png
  LongBlack-iOS/LongBlack-iOS/Global/Resources/Assets.xcassets/libraryCoffeCard.imageset/Contents.json
  LongBlack-iOS/LongBlack-iOS/Global/Resources/Assets.xcassets/libraryCoffeCard.imageset/list3_card.png
  LongBlack-iOS/LongBlack-iOS/Global/Resources/Assets.xcassets/libraryCoffeCard.imageset/list3_card@2x.png
  LongBlack-iOS/LongBlack-iOS/Global/Resources/Assets.xcassets/libraryCoffeCard.imageset/list3_card@3x.png
  LongBlack-iOS/LongBlack-iOS/Global/Resources/Assets.xcassets/sticker_small_empty.imageset/Contents.json
  LongBlack-iOS/LongBlack-iOS/Global/Resources/Assets.xcassets/sticker_small_empty.imageset/sticker_small_empty.png
  LongBlack-iOS/LongBlack-iOS/Global/Resources/Assets.xcassets/sticker_small_empty.imageset/sticker_small_empty@2x.png
  LongBlack-iOS/LongBlack-iOS/Global/Resources/Assets.xcassets/sticker_small_empty.imageset/sticker_small_empty@3x.png
  LongBlack-iOS/LongBlack-iOS/Global/Resources/Assets.xcassets/sticker_small_fill.imageset/Contents.json
  LongBlack-iOS/LongBlack-iOS/Global/Resources/Assets.xcassets/sticker_small_fill.imageset/sticker_small_fill.png
  LongBlack-iOS/LongBlack-iOS/Global/Resources/Assets.xcassets/sticker_small_fill.imageset/sticker_small_fill@2x.png
  LongBlack-iOS/LongBlack-iOS/Global/Resources/Assets.xcassets/sticker_small_fill.imageset/sticker_small_fill@3x.png
  LongBlack-iOS/LongBlack-iOS/Presentation/Library/Cell/LibraryCollectionViewCell.swift
  LongBlack-iOS/LongBlack-iOS/Presentation/Library/Cell/LibraryDescriptionCollectionViewCell.swift
  LongBlack-iOS/LongBlack-iOS/Presentation/Library/Cell/LibraryMakeCollectionViewCell.swift
  LongBlack-iOS/LongBlack-iOS/Presentation/Library/Cell/UnExchangedStampCollectionViewCell.swift
  LongBlack-iOS/LongBlack-iOS/Presentation/Library/LibraryViewController.swift
  LongBlack-iOS/LongBlack-iOS/Presentation/Library/Model/LibraryStampModel.swift
  LongBlack-iOS/LongBlack-iOS/Presentation/Library/View/ClassifyButtonView.swift
  LongBlack-iOS/LongBlack-iOS/Presentation/Library/View/CustomLibraryView.swift
  LongBlack-iOS/LongBlack-iOS/Presentation/Library/View/LibrarySegmentedControl.swift
  LongBlack-iOS/LongBlack-iOS/Presentation/Library/ViewController/LibraryPageViewController.swift
  LongBlack-iOS/LongBlack-iOS/Presentation/Library/ViewController/LibraryViewController.swift
  LongBlack-iOS/LongBlack-iOS/Presentation/Library/ViewController/MyBookmarkView.swift
  LongBlack-iOS/LongBlack-iOS/Presentation/Library/ViewController/MyNoteView.swift
  LongBlack-iOS/LongBlack-iOS/Presentation/Library/ViewController/MyStickerView.swift
Labels: feat, style, 민지
